[build]
  command = "npm run generate"
  publish = ".output/public"

[context.production.environment]
  # Fuerza Nuxt/Nitro a generar est√°tico en Netlify en lugar de usar el preset `netlify-legacy`
  NITRO_PRESET = "static"
